// Zweig — палитра эмодзи и поисковый индекс к ней.
//
// Индекс собран из имён Unicode (английские слова) плюс русские синонимы:
// без него поиск в палитре искать не по чему — сами символы не содержат
// текста. Ключевые слова разделены пробелом, совпадение ищется по началу
// слова, поэтому «серд» находит «сердце», а «cat» не находит
// «multiplication». Файл подключается перед app.js.

const EMOJI_DATA = {
    'smileys': ['😀','😃','😄','😁','😆','😅','🤣','😂','🙂','😊','😇','🥰','😍','🤩','😘','😗','😋','😛','😜','🤪','😝','🤑','🤗','🤭','🫢','🤫','🤔','🫡','🤐','🤨','😐','😑','😶','🫥','😏','😒','🙄','😬','😮‍💨','🤥','😌','😔','😪','🤤','😴','😷','🤒','🤕','🤢','🤮','🥵','🥶','🥴','😵','🤯','🤠','🥳','🥸','😎','🤓','🧐','😕','🫤','😟','🙁','😮','😯','😲','😳','🥺','🥹','😦','😧','😨','😰','😥','😢','😭','😱','😖','😣','😞','😓','😩','😫','🥱','😤','😡','😠','🤬','😈','👿','💀','☠️','💩','🤡','👹','👺','👻','👽','👾','🤖'],
    'gestures': ['👋','🤚','🖐️','✋','🖖','🫱','🫲','🫳','🫴','👌','🤌','🤏','✌️','🤞','🫰','🤟','🤘','🤙','👈','👉','👆','🖕','👇','☝️','🫵','👍','👎','✊','👊','🤛','🤜','👏','🙌','🫶','👐','🤲','🤝','🙏','✍️','💅','🤳','💪','🦾','🦿','🦵','🦶','👂','🦻','👃','🧠','🫀','🫁','🦷','🦴','👀','👁️','👅','👄'],
    'people': ['👶','👧','🧒','👦','👩','🧑','👨','👩‍🦱','🧑‍🦱','👨‍🦱','👩‍🦰','🧑‍🦰','👨‍🦰','👱‍♀️','👱','👱‍♂️','👩‍🦳','🧑‍🦳','👨‍🦳','👩‍🦲','🧑‍🦲','👨‍🦲','🧔‍♀️','🧔','🧔‍♂️','👵','🧓','👴','👲','👳‍♀️','👳','👳‍♂️','🧕','👮‍♀️','👮','👮‍♂️','👷‍♀️','👷','👷‍♂️','💂‍♀️','💂','💂‍♂️','🕵️‍♀️','🕵️','🕵️‍♂️','👩‍⚕️','🧑‍⚕️','👨‍⚕️','👩‍🌾','🧑‍🌾','👨‍🌾'],
    'nature': ['🐶','🐱','🐭','🐹','🐰','🦊','🐻','🐼','🐻‍❄️','🐨','🐯','🦁','🐮','🐷','🐸','🐵','🙈','🙉','🙊','🐒','🐔','🐧','🐦','🐤','🐣','🐥','🦆','🦅','🦉','🦇','🐺','🐗','🐴','🦄','🐝','🪱','🐛','🦋','🐌','🐞','🐜','🪰','🪲','🪳','🦟','🦗','🕷️','🦂','🐢','🐍','🦎','🦖','🦕','🐙','🦑','🦐','🦞','🦀','🐡','🐠','🐟','🐬','🐳','🐋','🦈','🪸','🐊','🐅','🐆','🦓','🦍','🦧','🐘','🦛','🦏','🐪','🐫','🦒','☀️','⛅','☁️','🌦️','🌧️','⛈️','🌩️','🌨️','❄️','☃️','⛄','💨','🌪️','🌫️','🌈','☔','💧','💦','🌊','🔥','⭐','🌟','✨','💫','☄️','🌙','🌕','🌗','🌑','🌓','🌚','🌝','🌞','💐','🌸','🌹','🥀','🌺','🌻','🌼','🌷','🌱','🪴','🌲','🌳','🌴','🌵','🌾','🌿','☘️','🍀','🍁','🍂','🍃'],
    'food': ['🍏','🍎','🍐','🍊','🍋','🍌','🍉','🍇','🍓','🫐','🍈','🍒','🍑','🥭','🍍','🥥','🥝','🍅','🍆','🥑','🥦','🥬','🥒','🌶️','🫑','🌽','🥕','🫒','🧄','🧅','🥔','🍠','🫘','🥐','🥯','🍞','🥖','🥨','🧀','🥚','🍳','🧈','🥞','🧇','🥓','🥩','🍗','🍖','🦴','🌭','🍔','🍟','🍕','🫓','🥪','🥙','🧆','🌮','🌯','🫔','🥗','🥘','🫕','🥫','🍝','🍜','🍲','🍛','🍣','🍱','🥟','🦪','🍤','🍙','🍚','🍘','🍥','🥠','🥮','🍢','🍡','🍧','🍨','🍦','🥧','🧁','🍰','🎂','🍮','🍭','🍬','🍫','🍿','🍩','🍪','☕','🫖','🍵','🧃','🥤','🧋','🍶','🍺','🍻','🥂','🍷','🥃','🍸','🍹','🧉','🍾','🧊','🥛','🍼'],
    'activities': ['⚽','🏀','🏈','⚾','🥎','🎾','🏐','🏉','🥏','🎱','🪀','🏓','🏸','🏒','🏑','🥍','🏏','🪃','🥅','⛳','🪁','🏹','🎣','🤿','🥊','🥋','🎽','🛹','🛼','🛷','⛸️','🥌','🎿','⛷️','🏂','🪂','🏋️','🤸','⛹️','🤺','🏇','🧘','🏄','🏊','🤽','🚣','🧗','🚵','🚴','🏆','🥇','🥈','🥉','🏅','🎖️','🏵️','🎗️','🎪','🎭','🎨','🎬','🎤','🎧','🎼','🎹','🥁','🪘','🎷','🎺','🪗','🎸','🪕','🎻','🎲','♟️','🎯','🎳','🎮','🕹️'],
    'travel': ['🚗','🚕','🚙','🚌','🚎','🏎️','🚓','🚑','🚒','🚐','🛻','🚚','🚛','🚜','🛵','🏍️','🛺','🚲','🛴','🛹','🛼','🚏','🛣️','🛤️','🛞','⛽','🚨','🚥','🚦','🛑','🚧','⚓','🛟','⛵','🛶','🚤','🛳️','⛴️','🛥️','🚢','✈️','🛩️','🛫','🛬','🪂','💺','🚁','🚟','🚠','🚡','🛰️','🚀','🌍','🌎','🌏','🌐','🗺️','🧭','🏔️','⛰️','🌋','🗻','🏕️','🏖️','🏜️','🏝️','🏞️'],
    'objects': ['⌚','📱','📲','💻','⌨️','🖥️','🖨️','🖱️','🖲️','🕹️','🗜️','💾','💿','📀','📼','📷','📸','📹','🎥','📽️','🎞️','📞','☎️','📟','📠','📺','📻','🎙️','🎚️','🎛️','🧭','⏱️','⏲️','⏰','🕰️','⌛','⏳','📡','🔋','🔌','💡','🔦','🕯️','🪔','🧯','🛢️','💸','💵','💴','💶','💷','🪙','💰','💳','💎','⚖️','🪜','🧰','🪛','🔧','🔨','⚒️','🛠️','⛏️','🪚','🔩','⚙️','🪤','🧱','⛓️','🧲','🔫','💣','🧨','🪓','🔪','🗡️','⚔️','🛡️','🚬','⚰️','🪦','⚱️','🏺','🔮','📿','🧿','🪬','💈','⚗️','🔭','🔬','🕳️','🩹','🩺','🩻','🩼','💊','💉','🩸','🧬','🦠','🧫','🧪','🌡️','🧹','🪠','🧺','🧻','🚽','🚰','🚿','🛁','🛀','🪥','🪒','🧴','🧷','🧹','🧺','🔑','🗝️','🚪','🪑','🛋️','🛏️','🛌','🧸','🪆','🖼️','🪞','🪟','🛒','🎁','🎈','🎏','🎀','🪄','🪅','🎊','🎉','🎎','🏮','🎐','🧧','✉️','📩','📨','📧','💌','📥','📤','📦','🏷️','🪧','📪','📫','📬','📭','📮','📯','📜','📃','📄','📑','🧾','📊','📈','📉','🗒️','🗓️','📆','📅','🗑️','📇','🗃️','🗳️','🗄️','📋','📁','📂','🗂️','🗞️','📰','📓','📔','📒','📕','📗','📘','📙','📚','📖','🔖','🧷','🔗','📎','🖇️','📐','📏','🧮','📌','📍','✂️','🖊️','🖋️','✒️','🖌️','🖍️','📝','✏️','🔍','🔎','🔏','🔐','🔒','🔓','👕','👖','🧥','👗','👔','👚','🩳','🩱','👘','🥻','🧣','🧤','🧦','👞','👟','🥾','🥿','👠','👡','👢','👑','👒','🎩','🎓','🧢','⛑️','💄','💍','👓','🕶️','🥽','🎒','👜','👛','👝','💼','🧳','☂️'],
    'symbols': ['❤️','🧡','💛','💚','💙','💜','🖤','🤍','🤎','💔','❤️‍🔥','❤️‍🩹','❣️','💕','💞','💓','💗','💖','💘','💝','💟','☮️','✝️','☪️','🕉️','☸️','✡️','🔯','🕎','☯️','☦️','🛐','⛎','♈','♉','♊','♋','♌','♍','♎','♏','♐','♑','♒','♓','🆔','⚛️','🉑','☢️','☣️','📴','📳','🈶','🈚','🈸','🈺','🈷️','✴️','🆚','💮','🉐','㊙️','㊗️','🈴','🈵','🈹','🈲','🅰️','🅱️','🆎','🆑','🅾️','🆘','❌','⭕','🛑','⛔','📛','🚫','💯','💢','♨️','🚷','🚯','🚳','🚱','🔞','📵','🚭','❗','❕','❓','❔','‼️','⁉️','🔅','🔆','〽️','⚠️','🚸','🔱','⚜️','🔰','♻️','✅','🈯','💹','❇️','✳️','❎','🌐','💠','Ⓜ️','🌀','💤','🏧','🚾','♿','🅿️','🛗','🈳','🈂️','🛂','🛃','🛄','🛅','🚹','🚺','🚼','⚧️','🚻','🚮','🎦','📶','🈁','🔣','ℹ️','🔤','🔡','🔠','🆖','🆗','🆙','🆒','🆕','🆓','0️⃣','1️⃣','2️⃣','3️⃣','4️⃣','5️⃣','6️⃣','7️⃣','8️⃣','9️⃣','🔟','🔢','#️⃣','*️⃣','⏏️','▶️','⏸️','⏯️','⏹️','⏺️','⏭️','⏮️','⏩','⏪','⏫','⏬','◀️','🔼','🔽','➡️','⬅️','⬆️','⬇️','↗️','↘️','↙️','↖️','↕️','↔️','↪️','↩️','⤴️','⤵️','🔀','🔁','🔂','🔄','🔃','🎵','🎶','➕','➖','➗','✖️','🟰','♾️','💲','💱','™️','©️','®️','〰️','➰','➿','🔚','🔙','🔛','🔝','🔜','✔️','☑️','🔘','🔴','🟠','🟡','🟢','🔵','🟣','⚫','⚪','🟤','🔺','🔻','🔸','🔹','🔶','🔷','🔳','🔲','▪️','▫️','◾','◽','◼️','◻️','🟥','🟧','🟨','🟩','🟦','🟪','⬛','⬜','🟫','🔈','🔇','🔉','🔊','🔔','🔕','📣','📢','💬','💭','🗯️','♠️','♣️','♥️','♦️','🃏','🎴','🀄','🕐','🕑','🕒','🕓','🕔','🕕','🕖','🕗','🕘','🕙','🕚','🕛'],
};

// эмодзи → слова, по которым его находит поиск (ru + en)
const EMOJI_KEYWORDS = {
    '😀': 'grinning face улыбка ухмылка лицо',
    '😃': 'smiling face open mouth улыбка лицо открытый рот',
    '😄': 'smiling face open mouth eyes улыбка лицо открытый рот глаза',
    '😁': 'grinning face smiling eyes улыбка ухмылка лицо глаза',
    '😆': 'smiling face open mouth tightly closed eyes улыбка лицо открытый рот зажмурился закрытый глаза',
    '😅': 'smiling face open mouth cold sweat улыбка лицо открытый рот холодный пот неловко упс',
    '🤣': 'rolling floor laughing катается пол смех хохот ржу лол lol',
    '😂': 'face tears joy лицо слёзы радость смех ржу лол lol',
    '🙂': 'slightly smiling face слегка улыбка лицо ок',
    '😊': 'smiling face eyes улыбка лицо глаза спасибо приятно',
    '😇': 'smiling face halo улыбка лицо нимб ангел',
    '🥰': 'smiling face eyes three hearts улыбка лицо глаза три сердечки любовь нежность',
    '😍': 'smiling face heart shaped eyes улыбка лицо сердце любовь глаза восторг влюблён',
    '🤩': 'grinning face star eyes улыбка ухмылка лицо звезда глаза',
    '😘': 'face throwing kiss лицо поцелуй чмок',
    '😗': 'kissing face поцелуй целует лицо',
    '😋': 'face savouring delicious food лицо вкусно',
    '😛': 'face stuck out tongue лицо высунут наружу язык',
    '😜': 'face stuck out tongue winking eye лицо высунут наружу язык подмигивает глаз',
    '🤪': 'grinning face one large small eye улыбка ухмылка лицо один большой маленький глаз',
    '😝': 'face stuck out tongue tightly closed eyes лицо высунут наружу язык зажмурился закрытый глаза',
    '🤑': 'money mouth face деньги рот лицо',
    '🤗': 'hugging face обнимает объятия лицо',
    '🤭': 'smiling face eyes hand covering mouth улыбка лицо глаза рука ладонь закрывает рот',
    '🫢': 'лицо рука рот ой face hand over mouth',
    '🤫': 'face finger covering closed lips лицо палец закрывает закрытый губы',
    '🤔': 'thinking face думает размышление лицо хм вопрос hmm',
    '🫡': 'честь салют лицо face salute',
    '🤐': 'zipper mouth face молния рот на замке лицо',
    '🤨': 'face one eyebrow raised лицо один бровь поднятая',
    '😐': 'neutral face нейтральное лицо',
    '😑': 'expressionless face без эмоций лицо',
    '😶': 'face without mouth лицо рот',
    '🫥': 'пунктир лицо невидимый face dotted',
    '😏': 'smirking face ухмылка лицо',
    '😒': 'unamused face недовольство лицо',
    '🙄': 'face rolling eyes лицо катается глаза',
    '😬': 'grimacing face гримаса лицо',
    '😮‍💨': 'face open mouth dash лицо открытый рот пар',
    '🤥': 'lying face врёт ложь лицо',
    '😌': 'relieved face облегчение лицо',
    '😔': 'pensive face грусть задумчивость лицо',
    '😪': 'sleepy face сонное лицо',
    '🤤': 'drooling face слюни лицо',
    '😴': 'sleeping face спит сон лицо спать',
    '😷': 'face medical mask лицо медицинская маска',
    '🤒': 'face thermometer лицо градусник температура болею',
    '🤕': 'face head bandage лицо голова повязка',
    '🤢': 'nauseated face тошнота лицо фу',
    '🤮': 'face open mouth vomiting лицо открытый рот рвота',
    '🥵': 'overheated face жара лицо',
    '🥶': 'freezing face холод мороз лицо',
    '🥴': 'face uneven eyes wavy mouth лицо кривой глаза волнистая рот',
    '😵': 'dizzy face головокружение лицо',
    '🤯': 'shocked face exploding head шок лицо взрыв голова мозга',
    '🤠': 'face cowboy hat лицо ковбой шляпа',
    '🥳': 'face party horn hat лицо вечеринка праздник рожок шляпа ура',
    '🥸': 'disguised face маскировка лицо',
    '😎': 'smiling face sunglasses улыбка лицо очки солнцезащитные',
    '🤓': 'nerd face ботаник очки лицо',
    '🧐': 'face monocle лицо монокль',
    '😕': 'confused face растерянность лицо',
    '🫤': 'кривое лицо face diagonal mouth',
    '😟': 'worried face тревога лицо',
    '🙁': 'slightly frowning face слегка хмурое лицо',
    '😮': 'face open mouth лицо открытый рот',
    '😯': 'hushed face молчание лицо',
    '😲': 'astonished face изумление лицо',
    '😳': 'flushed face смущение лицо',
    '🥺': 'face pleading eyes лицо умоляет глаза',
    '🥹': 'сдерживаю слёзы лицо face holding back tears',
    '😦': 'frowning face open mouth хмурое лицо открытый рот',
    '😧': 'anguished face страдание лицо',
    '😨': 'fearful face страх лицо',
    '😰': 'face open mouth cold sweat лицо открытый рот холодный пот',
    '😥': 'disappointed relieved face разочарование облегчение лицо',
    '😢': 'crying face плач слёзы лицо',
    '😭': 'loudly crying face громко плач слёзы лицо рыдаю',
    '😱': 'face screaming fear лицо крик страх ужас',
    '😖': 'confounded face досада лицо',
    '😣': 'persevering face упорство лицо',
    '😞': 'disappointed face разочарование лицо',
    '😓': 'face cold sweat лицо холодный пот',
    '😩': 'weary face усталость лицо',
    '😫': 'tired face усталость лицо',
    '🥱': 'yawning face зевает лицо',
    '😤': 'face look triumph лицо торжество',
    '😡': 'pouting face злость лицо',
    '😠': 'angry face злой лицо',
    '🤬': 'serious face symbols covering mouth серьёзное лицо символы закрывает рот',
    '😈': 'smiling face horns улыбка лицо',
    '👿': 'imp чёртик',
    '💀': 'skull череп',
    '☠️': 'skull crossbones череп кости',
    '💩': 'pile poo куча какашка фигня',
    '🤡': 'clown face клоун лицо',
    '👹': 'japanese ogre японский огр',
    '👺': 'japanese goblin японский гоблин',
    '👻': 'ghost привидение',
    '👽': 'extraterrestrial alien инопланетянин',
    '👾': 'alien monster инопланетянин монстр',
    '🤖': 'robot face робот лицо бот',
    '👋': 'waving hand машет привет рука ладонь',
    '🤚': 'raised back hand поднятая назад рука ладонь',
    '🖐️': 'raised hand fingers splayed поднятая рука ладонь пальцы растопырены',
    '✋': 'raised hand поднятая рука ладонь',
    '🖖': 'raised hand part between middle ring fingers поднятая рука ладонь часть средний спасательный круг пальцы',
    '🫱': 'рука вправо hand rightwards',
    '🫲': 'рука влево hand leftwards',
    '🫳': 'рука вниз ладонь hand palm down',
    '🫴': 'рука вверх ладонь hand palm up',
    '👌': 'ok hand окей рука ладонь ок хорошо',
    '🤌': 'pinched fingers пальцы',
    '🤏': 'pinching hand рука ладонь',
    '✌️': 'victory hand победа рука ладонь мир виктория',
    '🤞': 'hand index middle fingers crossed рука ладонь картотека средний пальцы скрещены',
    '🫰': 'пальцы деньги щелчок сердечко fingers money',
    '🤟': 'i love you hand любовь рука ладонь',
    '🤘': 'horns рога коза рок rock',
    '🤙': 'call me hand рука ладонь',
    '👈': 'white left pointing backhand index белый влево указывает тыльная картотека',
    '👉': 'white right pointing backhand index белый вправо указывает тыльная картотека',
    '👆': 'white up pointing backhand index белый вверх указывает тыльная картотека',
    '🖕': 'reversed hand middle finger extended рука ладонь средний палец',
    '👇': 'white down pointing backhand index белый вниз указывает тыльная картотека',
    '☝️': 'white up pointing index белый вверх указывает картотека',
    '🫵': 'указывает на тебя ты point at viewer',
    '👍': 'thumbs up палец большой вверх лайк класс нравится like',
    '👎': 'thumbs down палец большой вниз дизлайк',
    '✊': 'raised fist поднятая кулак',
    '👊': 'fisted hand рука ладонь',
    '🤛': 'left facing fist влево направлена кулак',
    '🤜': 'right facing fist вправо направлена кулак',
    '👏': 'clapping hands аплодисменты хлопает руки браво молодец bravo',
    '🙌': 'person raising both hands celebration человек руки',
    '🫶': 'сердце руками руки heart hands',
    '👐': 'open hands открытый руки',
    '🤲': 'palms up together вверх',
    '🤝': 'handshake рукопожатие договорились сделка deal',
    '🙏': 'person folded hands человек молитва руки спасибо пожалуйста молюсь please thanks',
    '✍️': 'writing hand пишет рука ладонь',
    '💅': 'nail polish ноготь маникюр лак',
    '🤳': 'selfie селфи',
    '💪': 'flexed biceps мускул сила бицепс качок',
    '🦾': 'mechanical arm механическая протез рука',
    '🦿': 'mechanical leg механическая протез ножка',
    '🦵': 'leg ножка',
    '🦶': 'foot ступня',
    '👂': 'ear ухо',
    '🦻': 'ear hearing aid ухо',
    '👃': 'nose нос',
    '🧠': 'brain мозг',
    '🫀': 'anatomical heart сердце любовь',
    '🫁': 'lungs лёгкие',
    '🦷': 'tooth зуб',
    '🦴': 'bone кость',
    '👀': 'eyes глаза смотрю глянул',
    '👁️': 'eye глаз',
    '👅': 'tongue язык',
    '👄': 'mouth рот',
    '👶': 'baby младенец ребёнок',
    '👧': 'girl девочка',
    '🧒': 'child ребёнок',
    '👦': 'boy мальчик',
    '👩': 'woman женщина',
    '🧑': 'adult взрослый',
    '👨': 'man мужчина',
    '👩‍🦱': 'woman curly hair женщина завиток волосы',
    '🧑‍🦱': 'adult curly hair взрослый завиток волосы',
    '👨‍🦱': 'man curly hair мужчина завиток волосы',
    '👩‍🦰': 'woman red hair женщина рыжий красный волосы',
    '🧑‍🦰': 'adult red hair взрослый рыжий красный волосы',
    '👨‍🦰': 'man red hair мужчина рыжий красный волосы',
    '👱‍♀️': 'person blond hair female человек блондин волосы',
    '👱': 'person blond hair человек блондин волосы',
    '👱‍♂️': 'person blond hair male человек блондин волосы',
    '👩‍🦳': 'woman white hair женщина белый волосы',
    '🧑‍🦳': 'adult white hair взрослый белый волосы',
    '👨‍🦳': 'man white hair мужчина белый волосы',
    '👩‍🦲': 'woman bald женщина лысый',
    '🧑‍🦲': 'adult bald взрослый лысый',
    '👨‍🦲': 'man bald мужчина лысый',
    '🧔‍♀️': 'bearded person female борода человек',
    '🧔': 'bearded person борода человек',
    '🧔‍♂️': 'bearded person male борода человек',
    '👵': 'older woman пожилой женщина',
    '🧓': 'older adult пожилой взрослый',
    '👴': 'older man пожилой мужчина',
    '👲': 'man gua pi mao мужчина',
    '👳‍♀️': 'man turban female мужчина тюрбан',
    '👳': 'man turban мужчина тюрбан',
    '👳‍♂️': 'man turban male мужчина тюрбан',
    '🧕': 'person headscarf человек платок',
    '👮‍♀️': 'police officer female полиция офицер',
    '👮': 'police officer полиция офицер',
    '👮‍♂️': 'police officer male полиция офицер',
    '👷‍♀️': 'construction worker female строитель рабочий',
    '👷': 'construction worker строитель рабочий',
    '👷‍♂️': 'construction worker male строитель рабочий',
    '💂‍♀️': 'guardsman female гвардеец',
    '💂': 'guardsman гвардеец',
    '💂‍♂️': 'guardsman male гвардеец',
    '🕵️‍♀️': 'sleuth spy female детектив шпион',
    '🕵️': 'sleuth spy детектив шпион',
    '🕵️‍♂️': 'sleuth spy male детектив шпион',
    '👩‍⚕️': 'woman staff aesculapius женщина жезл врач медицина',
    '🧑‍⚕️': 'adult staff aesculapius взрослый жезл врач медицина',
    '👨‍⚕️': 'man staff aesculapius мужчина жезл врач медицина',
    '👩‍🌾': 'woman ear rice женщина ухо рис',
    '🧑‍🌾': 'adult ear rice взрослый ухо рис',
    '👨‍🌾': 'man ear rice мужчина ухо рис',
    '🐶': 'dog face собака пёс лицо',
    '🐱': 'cat face кот кошка лицо',
    '🐭': 'mouse face мышь лицо',
    '🐹': 'hamster face хомяк лицо',
    '🐰': 'rabbit face кролик заяц лицо',
    '🦊': 'fox face лиса лицо',
    '🐻': 'bear face медведь лицо',
    '🐼': 'panda face панда лицо',
    '🐻‍❄️': 'bear face snowflake медведь лицо',
    '🐨': 'koala коала',
    '🐯': 'tiger face тигр лицо',
    '🦁': 'lion face лев лицо',
    '🐮': 'cow face корова лицо',
    '🐷': 'pig face свинья лицо',
    '🐸': 'frog face лягушка лицо',
    '🐵': 'monkey face обезьяна лицо',
    '🙈': 'see no evil monkey видит нет злой обезьяна',
    '🙉': 'hear no evil monkey слышит нет злой обезьяна',
    '🙊': 'speak no evil monkey говорит нет злой обезьяна',
    '🐒': 'monkey обезьяна',
    '🐔': 'chicken курица',
    '🐧': 'penguin пингвин',
    '🐦': 'bird птица',
    '🐤': 'baby chick младенец ребёнок цыплёнок',
    '🐣': 'hatching chick вылупляется цыплёнок',
    '🐥': 'front facing baby chick направлена младенец ребёнок цыплёнок',
    '🦆': 'duck утка',
    '🦅': 'eagle орёл',
    '🦉': 'owl сова',
    '🦇': 'bat летучая мышь',
    '🐺': 'wolf face волк лицо',
    '🐗': 'boar кабан',
    '🐴': 'horse face лошадь конь лицо',
    '🦄': 'unicorn face единорог лицо',
    '🐝': 'honeybee пчела bee',
    '🪱': 'worm червяк',
    '🐛': 'bug жук насекомое баг',
    '🦋': 'butterfly бабочка',
    '🐌': 'snail улитка',
    '🐞': 'lady beetle жук',
    '🐜': 'ant муравей',
    '🪰': 'fly муха',
    '🪲': 'beetle жук',
    '🪳': 'cockroach таракан',
    '🦟': 'mosquito комар',
    '🦗': 'cricket крикет',
    '🕷️': 'spider паук',
    '🦂': 'scorpion скорпион',
    '🐢': 'turtle черепаха',
    '🐍': 'snake змея',
    '🦎': 'lizard ящерица',
    '🦖': 't rex динозавр',
    '🦕': 'sauropod динозавр',
    '🐙': 'octopus осьминог',
    '🦑': 'squid кальмар',
    '🦐': 'shrimp креветка',
    '🦞': 'lobster омар',
    '🦀': 'crab краб',
    '🐡': 'blowfish рыба фугу',
    '🐠': 'tropical fish тропический рыба',
    '🐟': 'fish рыба',
    '🐬': 'dolphin дельфин',
    '🐳': 'spouting whale кит',
    '🐋': 'whale кит',
    '🦈': 'shark акула',
    '🪸': 'коралл coral',
    '🐊': 'crocodile крокодил',
    '🐅': 'tiger тигр',
    '🐆': 'leopard леопард',
    '🦓': 'zebra face зебра лицо',
    '🦍': 'gorilla горилла',
    '🦧': 'orangutan орангутан',
    '🐘': 'elephant слон',
    '🦛': 'hippopotamus бегемот',
    '🦏': 'rhinoceros носорог',
    '🐪': 'dromedary camel верблюд',
    '🐫': 'bactrian camel верблюд',
    '🦒': 'giraffe face жираф лицо',
    '☀️': 'black sun rays чёрный',
    '⛅': 'sun behind cloud солнце облако погода',
    '☁️': 'cloud облако тучи',
    '🌦️': 'white sun behind cloud rain белый',
    '🌧️': 'cloud rain дождь',
    '⛈️': 'thunder cloud rain гроза дождь молния storm',
    '🌩️': 'cloud lightning гроза молния',
    '🌨️': 'cloud snow снег',
    '❄️': 'snowflake снежинка снег зима snow',
    '☃️': 'snowman снеговик зима',
    '⛄': 'snowman without snow снег',
    '💨': 'dash пар',
    '🌪️': 'cloud tornado торнадо смерч',
    '🌫️': 'fog туман',
    '🌈': 'rainbow радуга',
    '☔': 'umbrella rain drops зонт дождь',
    '💧': 'droplet капля вода drop water',
    '💦': 'splashing sweat пот',
    '🌊': 'water wave вода',
    '🔥': 'fire огонь пожар',
    '⭐': 'white medium star белый средний звезда избранное',
    '🌟': 'glowing star звезда',
    '✨': 'sparkles искры блеск',
    '💫': 'dizzy головокружение',
    '☄️': 'comet комета',
    '🌙': 'crescent moon полумесяц луна',
    '🌕': 'full moon луна',
    '🌗': 'last quarter moon последний луна',
    '🌑': 'new moon новое луна',
    '🌓': 'first quarter moon луна',
    '🌚': 'new moon face новое луна лицо',
    '🌝': 'full moon face луна лицо',
    '🌞': 'sun face лицо',
    '💐': 'bouquet букет цветы',
    '🌸': 'cherry blossom цветок сакура вишня',
    '🌹': 'rose роза цветок',
    '🥀': 'wilted flower цветок',
    '🌺': 'hibiscus цветок гибискус',
    '🌻': 'sunflower подсолнух цветок',
    '🌼': 'blossom ромашка цветок flower',
    '🌷': 'tulip тюльпан цветок',
    '🌱': 'seedling росток растение',
    '🪴': 'potted plant растение горшок',
    '🌲': 'evergreen tree ёлка дерево хвойное',
    '🌳': 'deciduous tree дерево',
    '🌴': 'palm tree пальма дерево',
    '🌵': 'cactus кактус',
    '🌾': 'ear rice ухо рис',
    '🌿': 'herb веточка растение зелень',
    '☘️': 'shamrock клевер трилистник',
    '🍀': 'four leaf clover четыре',
    '🍁': 'maple leaf клён лист осень',
    '🍂': 'fallen leaf листья осень leaves',
    '🍃': 'leaf fluttering wind колокольчик',
    '🍏': 'green apple зелёный яблоко',
    '🍎': 'red apple рыжий красный яблоко',
    '🍐': 'pear груша',
    '🍊': 'tangerine мандарин',
    '🍋': 'lemon лимон',
    '🍌': 'banana банан',
    '🍉': 'watermelon арбуз',
    '🍇': 'grapes виноград',
    '🍓': 'strawberry клубника',
    '🫐': 'blueberries черника',
    '🍈': 'melon дыня',
    '🍒': 'cherries вишня',
    '🍑': 'peach персик',
    '🥭': 'mango манго',
    '🍍': 'pineapple ананас',
    '🥥': 'coconut кокос',
    '🥝': 'kiwifruit киви',
    '🍅': 'tomato помидор',
    '🍆': 'aubergine баклажан eggplant',
    '🥑': 'avocado авокадо',
    '🥦': 'broccoli брокколи',
    '🥬': 'leafy green зелёный',
    '🥒': 'cucumber огурец',
    '🌶️': 'hot pepper жарко перец',
    '🫑': 'bell pepper колокольчик перец',
    '🌽': 'ear maize ухо',
    '🥕': 'carrot морковь',
    '🫒': 'olive оливка',
    '🧄': 'garlic чеснок',
    '🧅': 'onion лук',
    '🥔': 'potato картошка',
    '🍠': 'roasted sweet potato картошка',
    '🫘': 'фасоль боб beans',
    '🥐': 'croissant круассан',
    '🥯': 'bagel бублик',
    '🍞': 'bread хлеб',
    '🥖': 'baguette bread багет хлеб',
    '🥨': 'pretzel крендель',
    '🧀': 'cheese wedge сыр кусок',
    '🥚': 'egg яйцо',
    '🍳': 'cooking готовка',
    '🧈': 'butter масло',
    '🥞': 'pancakes блины',
    '🧇': 'waffle вафля',
    '🥓': 'bacon бекон',
    '🥩': 'cut meat кусок мясо',
    '🍗': 'poultry leg курица ножка',
    '🍖': 'meat bone мясо кость',
    '🌭': 'hot dog жарко собака пёс хот дог',
    '🍔': 'hamburger бургер',
    '🍟': 'french fries французский картошка фри',
    '🍕': 'slice pizza пицца',
    '🫓': 'flatbread лепёшка',
    '🥪': 'sandwich сэндвич',
    '🥙': 'stuffed flatbread фаршированный лепёшка',
    '🧆': 'falafel фалафель',
    '🌮': 'taco тако',
    '🌯': 'burrito буррито',
    '🫔': 'tamale тамале',
    '🥗': 'green salad зелёный салат',
    '🥘': 'shallow pan food сковорода',
    '🫕': 'fondue фондю',
    '🥫': 'canned food консервы',
    '🍝': 'spaghetti спагетти паста',
    '🍜': 'steaming bowl горячий миска',
    '🍲': 'pot food кастрюля',
    '🍛': 'curry rice карри рис',
    '🍣': 'sushi суши',
    '🍱': 'bento box бэнто квадрат',
    '🥟': 'dumpling пельмень',
    '🦪': 'oyster устрица',
    '🍤': 'fried shrimp жареный креветка',
    '🍙': 'rice ball рис шар',
    '🍚': 'cooked rice рис',
    '🍘': 'rice cracker рис крекер',
    '🍥': 'fish cake swirl design рыба торт пирожное',
    '🥠': 'fortune cookie печенье',
    '🥮': 'moon cake луна торт пирожное',
    '🍢': 'oden одэн',
    '🍡': 'dango данго',
    '🍧': 'shaved ice лёд мороженое',
    '🍨': 'ice cream мороженое лёд',
    '🍦': 'soft ice cream мягкое мороженое лёд',
    '🥧': 'pie пирог',
    '🧁': 'cupcake капкейк',
    '🍰': 'shortcake пирог',
    '🎂': 'birthday cake день рождения торт пирожное',
    '🍮': 'custard пудинг',
    '🍭': 'lollipop леденец',
    '🍬': 'candy конфета',
    '🍫': 'chocolate bar шоколад столбчатый',
    '🍿': 'popcorn попкорн',
    '🍩': 'doughnut пончик',
    '🍪': 'cookie печенье',
    '☕': 'hot beverage жарко кофе перерыв',
    '🫖': 'teapot чайник чай',
    '🍵': 'teacup without handle чай кружка tea',
    '🧃': 'beverage box квадрат',
    '🥤': 'cup straw стакан напиток сок drink',
    '🧋': 'bubble tea облачко',
    '🍶': 'sake bottle cup бутылка',
    '🍺': 'beer mug пиво',
    '🍻': 'clinking beer mugs пиво кружки cheers',
    '🥂': 'clinking glasses бокалы шампанское тост cheers',
    '🍷': 'wine glass стекло лупа',
    '🥃': 'tumbler glass стекло лупа',
    '🍸': 'cocktail glass стекло лупа',
    '🍹': 'tropical drink тропический',
    '🧉': 'mate drink мате matе',
    '🍾': 'bottle popping cork бутылка',
    '🧊': 'ice cube мороженое лёд',
    '🥛': 'glass milk стекло лупа',
    '🍼': 'baby bottle младенец ребёнок бутылка',
    '⚽': 'soccer ball футбол мяч шар',
    '🏀': 'basketball hoop баскетбол мяч',
    '🏈': 'american football американский футбол мяч',
    '⚾': 'baseball бейсбол',
    '🥎': 'softball софтбол',
    '🎾': 'tennis racquet ball теннис ракетка шар',
    '🏐': 'volleyball волейбол',
    '🏉': 'rugby football регби футбол мяч',
    '🥏': 'flying disc летающий диск фрисби',
    '🎱': 'billiards бильярд шар восемь',
    '🪀': 'yo йо',
    '🏓': 'table tennis paddle ball теннис шар',
    '🏸': 'badminton racquet shuttlecock бадминтон ракетка',
    '🏒': 'ice hockey stick puck мороженое лёд хоккей',
    '🏑': 'field hockey stick ball поле хоккей шар',
    '🥍': 'lacrosse stick ball лакросс шар',
    '🏏': 'cricket bat ball крикет летучая мышь шар',
    '🪃': 'boomerang бумеранг',
    '🥅': 'goal net ворота гол сетка',
    '⛳': 'flag hole флаг дыра',
    '🪁': 'kite воздушный змей',
    '🏹': 'bow arrow лук стрелка',
    '🎣': 'fishing pole fish рыбалка удочка рыба',
    '🤿': 'diving mask дайвинг маска',
    '🥊': 'boxing glove бокс перчатка',
    '🥋': 'martial arts uniform единоборства искусство форма кимоно',
    '🎽': 'running shirt sash бег майка',
    '🛹': 'skateboard скейт',
    '🛼': 'roller skate ролики коньки',
    '🛷': 'sled санки',
    '⛸️': 'ice skate мороженое лёд коньки',
    '🥌': 'curling stone кёрлинг камень',
    '🎿': 'ski boot лыжи',
    '⛷️': 'skier лыжник',
    '🏂': 'snowboarder сноуборд',
    '🪂': 'parachute парашют',
    '🏋️': 'weight lifter штанга штангист',
    '🤸': 'person doing cartwheel человек',
    '⛹️': 'person ball человек шар',
    '🤺': 'fencer фехтование',
    '🏇': 'horse racing лошадь конь скачки гонка',
    '🧘': 'person lotus position человек йога медитация поза',
    '🏄': 'surfer сёрфинг',
    '🏊': 'swimmer плавание',
    '🤽': 'water polo вода поло',
    '🚣': 'rowboat лодка гребля',
    '🧗': 'person climbing человек скалолазание',
    '🚵': 'mountain bicyclist горный',
    '🚴': 'bicyclist велосипедист велосипед cyclist bike',
    '🏆': 'trophy кубок трофей',
    '🥇': 'first place medal место медаль',
    '🥈': 'second place medal место медаль',
    '🥉': 'third place medal место медаль',
    '🏅': 'sports medal спорт медаль',
    '🎖️': 'military medal военная медаль',
    '🏵️': 'rosette розетка',
    '🎗️': 'reminder ribbon напоминание бант лента',
    '🎪': 'circus tent цирк палатка',
    '🎭': 'performing arts театр искусство',
    '🎨': 'artist palette художник палитра',
    '🎬': 'clapper board кино хлопушка доска',
    '🎤': 'microphone микрофон',
    '🎧': 'headphone наушники',
    '🎼': 'musical score музыка ноты',
    '🎹': 'musical keyboard музыка клавиши пианино',
    '🥁': 'drum drumsticks бочка',
    '🪘': 'long drum бочка',
    '🎷': 'saxophone саксофон',
    '🎺': 'trumpet труба',
    '🪗': 'accordion аккордеон',
    '🎸': 'guitar гитара',
    '🪕': 'banjo банджо',
    '🎻': 'violin скрипка',
    '🎲': 'game die игра кубик кости',
    '♟️': 'black chess pawn чёрный шахматы пешка',
    '🎯': 'direct hit дартс мишень попадание',
    '🎳': 'bowling боулинг',
    '🎮': 'video game видео игра',
    '🕹️': 'joystick джойстик',
    '🚗': 'automobile машина автомобиль',
    '🚕': 'taxi такси',
    '🚙': 'recreational vehicle фургон транспорт',
    '🚌': 'bus автобус',
    '🚎': 'trolleybus троллейбус',
    '🏎️': 'racing car скачки гонка машина автомобиль',
    '🚓': 'police car полиция машина автомобиль',
    '🚑': 'ambulance скорая помощь',
    '🚒': 'fire engine огонь машина',
    '🚐': 'minibus микроавтобус',
    '🛻': 'pickup truck пикап грузовик',
    '🚚': 'delivery truck доставка грузовик',
    '🚛': 'articulated lorry фура',
    '🚜': 'tractor трактор',
    '🛵': 'motor scooter мото скутер самокат',
    '🏍️': 'racing motorcycle скачки гонка мотоцикл',
    '🛺': 'auto rickshaw авто рикша',
    '🚲': 'bicycle велосипед',
    '🛴': 'scooter скутер самокат',
    '🚏': 'bus stop автобус стоп остановка',
    '🛣️': 'motorway шоссе',
    '🛤️': 'railway track железная дорога рельсы',
    '🛞': 'колесо wheel',
    '⛽': 'fuel pump заправка бензин колонка',
    '🚨': 'police cars revolving light полиция вращающиеся свет фонарь',
    '🚥': 'horizontal traffic light горизонтальный светофор свет фонарь',
    '🚦': 'vertical traffic light вертикальный светофор свет фонарь',
    '🛑': 'octagonal восьмиугольный',
    '🚧': 'construction строитель',
    '⚓': 'anchor якорь',
    '🛟': 'спасательный круг ring buoy',
    '⛵': 'sailboat парусник яхта',
    '🛶': 'canoe каноэ',
    '🚤': 'speedboat катер',
    '🛳️': 'passenger ship пассажирский корабль',
    '⛴️': 'ferry паром',
    '🛥️': 'motor boat мото лодка',
    '🚢': 'ship корабль',
    '✈️': 'airplane самолёт',
    '🛩️': 'small airplane маленький самолёт',
    '🛫': 'airplane departure самолёт вылет',
    '🛬': 'airplane arriving самолёт',
    '💺': 'seat кресло',
    '🚁': 'helicopter вертолёт',
    '🚟': 'suspension railway фуникулёр железная дорога рельсы',
    '🚠': 'mountain cableway горный канатная дорога',
    '🚡': 'aerial tramway канатная трамвай',
    '🛰️': 'satellite спутник',
    '🚀': 'rocket ракета запуск релиз launch',
    '🌍': 'earth globe europe africa земля планета глобус',
    '🌎': 'earth globe americas земля планета глобус',
    '🌏': 'earth globe asia australia земля планета глобус',
    '🌐': 'globe meridians глобус меридианы',
    '🗺️': 'world map карта',
    '🧭': 'compass компас',
    '🏔️': 'snow capped mountain снег заснеженный горный',
    '⛰️': 'mountain горный',
    '🌋': 'volcano вулкан',
    '🗻': 'mount fuji фудзи гора',
    '🏕️': 'camping кемпинг палатка',
    '🏖️': 'beach umbrella пляж',
    '🏜️': 'desert пустыня',
    '🏝️': 'desert island пустыня остров',
    '🏞️': 'national park парк',
    '⌚': 'watch часы',
    '📱': 'mobile phone мобильный телефон',
    '📲': 'mobile phone rightwards arrow at left мобильный телефон вправо стрелка влево',
    '💻': 'personal computer персональный компьютер ноутбук работа',
    '⌨️': 'keyboard клавиши пианино',
    '🖥️': 'desktop computer компьютер',
    '🖨️': 'printer принтер',
    '🖱️': 'three button mouse три кнопка мышь',
    '🖲️': 'trackball трекбол',
    '🗜️': 'compression тиски зажим clamp',
    '💾': 'floppy disk дискета диск',
    '💿': 'optical disc диск фрисби',
    '📀': 'dvd двд',
    '📼': 'videocassette кассета',
    '📷': 'camera камера фото',
    '📸': 'camera flash камера фото вспышка',
    '📹': 'video camera видео камера фото',
    '🎥': 'movie camera кино камера фото',
    '📽️': 'film projector плёнка кино проектор',
    '🎞️': 'film frames плёнка кино кадры',
    '📞': 'telephone receiver телефон трубка звонок',
    '☎️': 'black telephone чёрный телефон',
    '📟': 'pager пейджер',
    '📠': 'fax machine факс машина',
    '📺': 'television телевизор',
    '📻': 'radio радио',
    '🎙️': 'studio microphone студия микрофон',
    '🎚️': 'level slider уровень ползунок',
    '🎛️': 'control knobs управление ручки',
    '⏱️': 'stopwatch секундомер',
    '⏲️': 'timer clock таймер часы',
    '⏰': 'alarm clock будильник часы напоминание',
    '🕰️': 'mantelpiece clock часы',
    '⌛': 'hourglass песочные часы',
    '⏳': 'hourglass flowing sand песочные часы идут песок',
    '📡': 'satellite antenna спутник антенна',
    '🔋': 'battery батарея',
    '🔌': 'electric plug электрический вилка розетка',
    '💡': 'electric light bulb электрический свет фонарь лампочка идея',
    '🔦': 'electric torch электрический',
    '🕯️': 'candle свеча',
    '🪔': 'diya lamp лампа',
    '🧯': 'fire extinguisher огонь огнетушитель',
    '🛢️': 'oil drum нефть бочка',
    '💸': 'money wings деньги',
    '💵': 'banknote dollar банкнота деньги доллар',
    '💴': 'banknote yen банкнота деньги иена',
    '💶': 'banknote euro банкнота деньги евро',
    '💷': 'banknote pound банкнота деньги фунт',
    '🪙': 'coin монета',
    '💰': 'money bag деньги мешок бюджет',
    '💳': 'credit card кредитная карта карточка',
    '💎': 'gem stone алмаз бриллиант камень',
    '⚖️': 'scales весы правосудие balance scale',
    '🪜': 'ladder лестница',
    '🧰': 'toolbox ящик инструментов',
    '🪛': 'screwdriver отвёртка',
    '🔧': 'wrench ключ гаечный',
    '🔨': 'hammer молоток',
    '⚒️': 'hammer pick молоток кирка',
    '🛠️': 'hammer wrench молоток ключ гаечный',
    '⛏️': 'pick кирка',
    '🪚': 'carpentry saw пила',
    '🔩': 'nut bolt гайка болт',
    '⚙️': 'gear шестерёнка',
    '🪤': 'mouse trap мышь мышеловка',
    '🧱': 'brick кирпич',
    '⛓️': 'chains цепи',
    '🧲': 'magnet магнит',
    '🔫': 'pistol пистолет',
    '💣': 'bomb бомба',
    '🧨': 'firecracker петарда',
    '🪓': 'axe топор',
    '🔪': 'hocho нож кухонный knife',
    '🗡️': 'dagger knife кинжал нож',
    '⚔️': 'crossed swords скрещены мечи',
    '🛡️': 'shield щит',
    '🚬': 'smoking курение',
    '⚰️': 'coffin гроб',
    '🪦': 'headstone надгробие',
    '⚱️': 'funeral urn урна',
    '🏺': 'amphora амфора',
    '🔮': 'crystal ball хрустальный шар',
    '📿': 'prayer beads чётки бусы',
    '🧿': 'nazar amulet амулет',
    '🪬': 'амулет хамса hamsa',
    '💈': 'barber pole парикмахерская удочка',
    '⚗️': 'alembic колба',
    '🔭': 'telescope телескоп',
    '🔬': 'microscope микроскоп',
    '🕳️': 'hole дыра',
    '🩹': 'adhesive bandage пластырь повязка',
    '🩺': 'stethoscope стетоскоп',
    '🩻': 'рентген x-ray',
    '🩼': 'костыль crutch',
    '💊': 'pill таблетка',
    '💉': 'syringe шприц',
    '🩸': 'drop blood капля кровь',
    '🧬': 'dna double helix днк двойной',
    '🦠': 'microbe микроб',
    '🧫': 'petri dish чашка петри',
    '🧪': 'test tube пробирка',
    '🌡️': 'thermometer градусник температура',
    '🧹': 'broom метла',
    '🪠': 'plunger вантуз',
    '🧺': 'basket корзина',
    '🧻': 'roll paper рулон бумага',
    '🚽': 'toilet туалет',
    '🚰': 'potable water питьевая вода',
    '🚿': 'shower душ',
    '🛁': 'bathtub ванна',
    '🛀': 'bath ванна',
    '🪥': 'toothbrush зубная щётка',
    '🪒': 'razor бритва',
    '🧴': 'lotion bottle лосьон бутылка',
    '🧷': 'safety pin английская булавка',
    '🔑': 'key ключ',
    '🗝️': 'old key старый ключ',
    '🚪': 'door дверь',
    '🪑': 'chair стул',
    '🛋️': 'couch lamp диван лампа',
    '🛏️': 'bed кровать',
    '🛌': 'sleeping accommodation спит сон',
    '🧸': 'teddy bear мишка медведь',
    '🪆': 'nesting dolls матрёшка куклы',
    '🖼️': 'frame picture картина',
    '🪞': 'mirror зеркало',
    '🪟': 'window окно',
    '🛒': 'shopping trolley покупки тележка',
    '🎁': 'wrapped present подарок',
    '🎈': 'balloon облачко',
    '🎏': 'carp streamer карп вымпел',
    '🎀': 'ribbon бант лента',
    '🪄': 'magic wand волшебная палочка',
    '🪅': 'pinata пиньята',
    '🎊': 'confetti ball конфетти шар ура поздравляю',
    '🎉': 'party popper вечеринка праздник хлопушка ура поздравляю congrats',
    '🎎': 'japanese dolls японский куклы',
    '🏮': 'izakaya lantern фонарь',
    '🎐': 'wind chime колокольчик',
    '🧧': 'red gift envelope рыжий красный подарок конверт письмо',
    '✉️': 'envelope конверт письмо',
    '📩': 'envelope downwards arrow above конверт письмо вниз стрелка',
    '📨': 'incoming envelope входящий конверт письмо',
    '📧': 'e mail почта письмо email',
    '💌': 'love letter любовь письмо буква любовное',
    '📥': 'inbox tray входящие лоток',
    '📤': 'outbox tray исходящие лоток',
    '📦': 'package посылка коробка',
    '🏷️': 'label ярлык',
    '🪧': 'placard табличка',
    '📪': 'closed mailbox lowered flag закрытый почтовый ящик флаг',
    '📫': 'closed mailbox raised flag закрытый почтовый ящик поднятая флаг',
    '📬': 'open mailbox raised flag открытый почтовый ящик поднятая флаг',
    '📭': 'open mailbox lowered flag открытый почтовый ящик флаг',
    '📮': 'postbox почтовый ящик',
    '📯': 'postal horn почтовый рожок',
    '📜': 'scroll свиток',
    '📃': 'page curl страница лист загнутая',
    '📄': 'page facing up страница лист направлена вверх',
    '📑': 'bookmark tabs закладка вкладки',
    '🧾': 'receipt чек',
    '📊': 'bar chart столбчатый график диаграмма',
    '📈': 'chart upwards trend график диаграмма вверх тренд рост метрики',
    '📉': 'chart downwards trend график диаграмма вниз тренд падение метрики',
    '🗒️': 'spiral note pad спиральный нота блокнот',
    '🗓️': 'spiral calendar pad спиральный календарь блокнот',
    '📆': 'tear off calendar отрывной календарь',
    '📅': 'calendar календарь',
    '🗑️': 'wastebasket корзина мусор',
    '📇': 'card index карта карточка картотека',
    '🗃️': 'card file box карта карточка файл папка квадрат',
    '🗳️': 'ballot box галочка квадрат',
    '🗄️': 'file cabinet файл папка шкаф картотека',
    '📋': 'clipboard планшет буфер',
    '📁': 'file folder файл папка',
    '📂': 'open file folder открытый файл папка',
    '🗂️': 'card index dividers карта карточка картотека разделители',
    '🗞️': 'rolled up newspaper свёрнутая вверх газета',
    '📰': 'newspaper газета',
    '📓': 'notebook тетрадь',
    '📔': 'notebook decorative cover тетрадь декоративная обложка',
    '📒': 'ledger журнал',
    '📕': 'closed book закрытый книга',
    '📗': 'green book зелёный книга',
    '📘': 'blue book синий книга',
    '📙': 'orange book оранжевый книга',
    '📚': 'books книги',
    '📖': 'open book открытый книга',
    '🔖': 'bookmark закладка',
    '🔗': 'link ссылка',
    '📎': 'paperclip скрепка файл вложение',
    '🖇️': 'linked paperclips связанные',
    '📐': 'triangular ruler треугольная линейка',
    '📏': 'straight ruler прямая линейка',
    '🧮': 'abacus счёты',
    '📌': 'pushpin кнопка важно пин',
    '📍': 'round pushpin круглая кнопка',
    '✂️': 'black scissors чёрный ножницы',
    '🖊️': 'lower left ballpoint pen влево ручка',
    '🖋️': 'lower left fountain pen влево перьевая ручка',
    '✒️': 'black nib чёрный перо',
    '🖌️': 'lower left paintbrush влево кисть',
    '🖍️': 'lower left crayon влево мелок',
    '📝': 'memo записка',
    '✏️': 'pencil карандаш',
    '🔍': 'left pointing magnifying glass влево указывает лупа поиск стекло',
    '🔎': 'right pointing magnifying glass вправо указывает лупа поиск стекло',
    '🔏': 'lock ink pen замок закрыто чернила ручка',
    '🔐': 'closed lock key закрытый замок закрыто ключ',
    '🔒': 'lock замок закрыто секретно',
    '🔓': 'open lock открытый замок закрыто',
    '👕': 't shirt майка',
    '👖': 'jeans джинсы штаны',
    '🧥': 'coat куртка пальто',
    '👗': 'dress платье',
    '👔': 'necktie галстук рубашка tie',
    '👚': 'womans clothes блузка кофта blouse',
    '🩳': 'shorts шорты',
    '🩱': 'one piece swimsuit один',
    '👘': 'kimono кимоно',
    '🥻': 'sari сари',
    '🧣': 'scarf шарф',
    '🧤': 'gloves перчатки',
    '🧦': 'socks носки',
    '👞': 'mans shoe ботинок туфля',
    '👟': 'athletic shoe кроссовок кроссовки sneaker',
    '🥾': 'hiking boot ботинок походный',
    '🥿': 'flat shoe балетка туфля',
    '👠': 'high heeled shoe громко',
    '👡': 'womans sandal босоножка сандалия',
    '👢': 'womans boots сапог boot',
    '👑': 'crown корона',
    '👒': 'womans hat шляпа',
    '🎩': 'top hat вверх шляпа',
    '🎓': 'graduation cap выпускник шапочка',
    '🧢': 'billed cap кепка',
    '⛑️': 'helmet white cross белый крест',
    '💄': 'lipstick помада косметика',
    '💍': 'ring спасательный круг',
    '👓': 'eyeglasses очки glasses',
    '🕶️': 'dark sunglasses очки солнцезащитные',
    '🥽': 'goggles очки защитные',
    '🎒': 'school satchel рюкзак backpack',
    '👜': 'handbag сумка',
    '👛': 'purse кошелёк',
    '👝': 'pouch сумочка клатч',
    '💼': 'briefcase портфель работа',
    '🧳': 'luggage чемодан багаж',
    '☂️': 'umbrella зонт',
    '❤️': 'heavy black heart жирный чёрный сердце любовь лайк сердечко',
    '🧡': 'orange heart оранжевый сердце любовь оранжевое',
    '💛': 'yellow heart жёлтый сердце любовь',
    '💚': 'green heart зелёный сердце любовь',
    '💙': 'blue heart синий сердце любовь',
    '💜': 'purple heart фиолетовый сердце любовь',
    '🖤': 'black heart чёрный сердце любовь',
    '🤍': 'white heart белый сердце любовь',
    '🤎': 'brown heart коричневый сердце любовь',
    '💔': 'broken heart разбитое сердце любовь',
    '❤️‍🔥': 'heavy black heart fire жирный чёрный сердце любовь огонь',
    '❤️‍🩹': 'heavy black heart adhesive bandage жирный чёрный сердце любовь пластырь повязка',
    '❣️': 'heavy heart exclamation mark ornament жирный сердце любовь восклицательный знак',
    '💕': 'two hearts два сердечки любовь сердца',
    '💞': 'revolving hearts вращающиеся сердечки любовь',
    '💓': 'beating heart бьётся сердце любовь',
    '💗': 'growing heart растёт сердце любовь',
    '💖': 'sparkling heart сверкающее сердце любовь',
    '💘': 'heart arrow сердце любовь стрелка',
    '💝': 'heart ribbon сердце любовь бант лента',
    '💟': 'heart decoration сердце любовь украшение',
    '☮️': 'peace мир',
    '✝️': 'latin cross латинский крест',
    '☪️': 'star crescent звезда полумесяц',
    '🕉️': 'om ом',
    '☸️': 'wheel dharma колесо дхарма',
    '✡️': 'star david звезда давида',
    '🔯': 'six pointed star middle dot шесть конечная звезда средний точка',
    '🕎': 'menorah nine branches менора девять',
    '☯️': 'yin yang инь ян',
    '☦️': 'orthodox cross православный крест',
    '🛐': 'place worship место поклонение',
    '⛎': 'ophiuchus змееносец',
    '♈': 'aries овен',
    '♉': 'taurus телец',
    '♊': 'gemini близнецы',
    '♋': 'cancer рак',
    '♌': 'leo лев',
    '♍': 'virgo дева',
    '♎': 'libra весы',
    '♏': 'scorpius скорпион',
    '♐': 'sagittarius стрелец',
    '♑': 'capricorn козерог',
    '♒': 'aquarius водолей',
    '♓': 'pisces рыбы',
    '🆔': 'squared id в квадрате',
    '⚛️': 'atom атом',
    '🉑': 'circled ideograph accept в кружке иероглиф',
    '☢️': 'radioactive радиация',
    '☣️': 'biohazard биологическая опасность',
    '📴': 'mobile phone off мобильный телефон отрывной',
    '📳': 'vibration mode вибрация режим',
    '🈶': 'squared cjk unified ideograph 6709 в квадрате иероглиф',
    '🈚': 'squared cjk unified ideograph 7121 в квадрате иероглиф',
    '🈸': 'squared cjk unified ideograph 7533 в квадрате иероглиф',
    '🈺': 'squared cjk unified ideograph 55b6 в квадрате иероглиф',
    '🈷️': 'squared cjk unified ideograph 6708 в квадрате иероглиф',
    '✴️': 'eight pointed black star восемь конечная чёрный звезда',
    '🆚': 'squared vs в квадрате',
    '💮': 'white flower белый цветок',
    '🉐': 'circled ideograph advantage в кружке иероглиф',
    '㊙️': 'circled ideograph secret в кружке иероглиф',
    '㊗️': 'circled ideograph congratulation в кружке иероглиф',
    '🈴': 'squared cjk unified ideograph 5408 в квадрате иероглиф',
    '🈵': 'squared cjk unified ideograph 6e80 в квадрате иероглиф',
    '🈹': 'squared cjk unified ideograph 5272 в квадрате иероглиф',
    '🈲': 'squared cjk unified ideograph 7981 в квадрате иероглиф',
    '🅰️': 'negative squared latin capital letter инверсный в квадрате латинский заглавная письмо буква',
    '🅱️': 'negative squared latin capital letter b инверсный в квадрате латинский заглавная письмо буква',
    '🆎': 'negative squared ab инверсный в квадрате',
    '🆑': 'squared cl в квадрате',
    '🅾️': 'negative squared latin capital letter o инверсный в квадрате латинский заглавная письмо буква',
    '🆘': 'squared sos в квадрате сос помощь',
    '❌': 'cross mark крест знак ошибка нет отмена',
    '⭕': 'heavy large circle жирный большой круг',
    '⛔': 'no entry нет въезд запрещён',
    '📛': 'name badge бейдж',
    '🚫': 'no entry нет въезд запрещён',
    '💯': 'hundred points сто баллов',
    '💢': 'anger гнев',
    '♨️': 'hot springs жарко источники',
    '🚷': 'no pedestrians нет пешеходы',
    '🚯': 'do not litter мусор',
    '🚳': 'no bicycles нет велосипеды',
    '🚱': 'non potable water не питьевая вода',
    '🔞': 'no one under eighteen нет один',
    '📵': 'no mobile phones нет мобильный телефон телефоны',
    '🚭': 'no smoking нет курение',
    '❗': 'heavy exclamation mark жирный восклицательный знак важно',
    '❕': 'white exclamation mark ornament белый восклицательный знак',
    '❓': 'black question mark ornament чёрный вопрос знак',
    '❔': 'white question mark ornament белый вопрос знак',
    '‼️': 'double exclamation mark двойной восклицательный знак',
    '⁉️': 'exclamation question mark восклицательный вопрос знак',
    '🔅': 'low brightness тихо',
    '🔆': 'high brightness громко',
    '〽️': 'part alternation mark часть чередование знак',
    '⚠️': 'warning внимание предупреждение осторожно',
    '🚸': 'children crossing дети переход',
    '🔱': 'trident emblem трезубец эмблема',
    '⚜️': 'fleur de lis лилия',
    '🔰': 'japanese beginner японский новичок',
    '♻️': 'black universal recycling чёрный переработка',
    '✅': 'white heavy check mark белый жирный галочка знак готово сделано done ok',
    '🈯': 'squared cjk unified ideograph 6307 в квадрате иероглиф',
    '💹': 'chart upwards trend yen график диаграмма вверх тренд иена',
    '❇️': 'sparkle искра',
    '✳️': 'eight spoked asterisk восемь звёздочка',
    '❎': 'negative squared cross mark инверсный в квадрате крест знак ошибка нет',
    '💠': 'diamond shape dot inside ромб точка внутри',
    'Ⓜ️': 'circled latin capital letter m в кружке латинский заглавная письмо буква',
    '🌀': 'cyclone циклон',
    '💤': 'sleeping спит сон',
    '🏧': 'automated teller machine банкомат машина',
    '🚾': 'water closet вода',
    '♿': 'wheelchair инвалидная коляска',
    '🅿️': 'negative squared latin capital letter p инверсный в квадрате латинский заглавная письмо буква',
    '🛗': 'elevator лифт',
    '🈳': 'squared cjk unified ideograph 7a7a в квадрате иероглиф',
    '🈂️': 'squared katakana sa в квадрате',
    '🛂': 'passport control паспорт управление',
    '🛃': 'customs таможня',
    '🛄': 'baggage claim багаж выдача',
    '🛅': 'left luggage влево',
    '🚹': 'mens мужской туалет men',
    '🚺': 'womens женский туалет women',
    '🚼': 'baby младенец ребёнок',
    '⚧️': 'male stroke female трансгендер transgender',
    '🚻': 'restroom туалет',
    '🚮': 'put litter its place мусор место',
    '🎦': 'cinema кино',
    '📶': 'antenna bars антенна',
    '🈁': 'squared katakana koko в квадрате',
    '🔣': 'input symbols ввод символы',
    'ℹ️': 'information source информация',
    '🔤': 'input latin letters ввод латинский буквы',
    '🔡': 'input latin small letters ввод латинский маленький буквы',
    '🔠': 'input latin capital letters ввод латинский заглавная буквы',
    '🆖': 'squared ng в квадрате нет',
    '🆗': 'squared ok в квадрате окей',
    '🆙': 'squared up exclamation mark в квадрате вверх восклицательный знак',
    '🆒': 'squared cool в квадрате круто',
    '🆕': 'squared new в квадрате новое',
    '🆓': 'squared free в квадрате бесплатно',
    '0️⃣': 'digit zero keycap цифра ноль клавиша',
    '1️⃣': 'digit one keycap цифра один клавиша',
    '2️⃣': 'digit two keycap цифра два клавиша',
    '3️⃣': 'digit three keycap цифра три клавиша',
    '4️⃣': 'digit four keycap цифра четыре клавиша',
    '5️⃣': 'digit five keycap цифра пять клавиша',
    '6️⃣': 'digit six keycap цифра шесть клавиша',
    '7️⃣': 'digit seven keycap цифра семь клавиша',
    '8️⃣': 'digit eight keycap цифра восемь клавиша',
    '9️⃣': 'digit nine keycap цифра девять клавиша',
    '🔟': 'keycap ten клавиша десять',
    '🔢': 'input numbers ввод',
    '#️⃣': 'number keycap номер решётка клавиша',
    '*️⃣': 'asterisk keycap звёздочка клавиша',
    '⏏️': 'eject извлечь',
    '▶️': 'black right pointing triangle чёрный вправо указывает треугольник',
    '⏸️': 'double vertical bar двойной вертикальный столбчатый',
    '⏯️': 'black right pointing triangle double vertical bar чёрный вправо указывает треугольник двойной вертикальный столбчатый',
    '⏹️': 'black square stop чёрный квадрат стоп остановка',
    '⏺️': 'black circle record чёрный круг запись',
    '⏭️': 'black right pointing double triangle vertical bar чёрный вправо указывает двойной треугольник вертикальный столбчатый',
    '⏮️': 'black left pointing double triangle vertical bar чёрный влево указывает двойной треугольник вертикальный столбчатый',
    '⏩': 'black right pointing double triangle чёрный вправо указывает двойной треугольник',
    '⏪': 'black left pointing double triangle чёрный влево указывает двойной треугольник',
    '⏫': 'black up pointing double triangle чёрный вверх указывает двойной треугольник',
    '⏬': 'black down pointing double triangle чёрный вниз указывает двойной треугольник',
    '◀️': 'black left pointing triangle чёрный влево указывает треугольник',
    '🔼': 'up pointing small red triangle вверх указывает маленький рыжий красный треугольник',
    '🔽': 'down pointing small red triangle вниз указывает маленький рыжий красный треугольник',
    '➡️': 'black rightwards arrow чёрный вправо стрелка',
    '⬅️': 'leftwards black arrow влево чёрный стрелка',
    '⬆️': 'upwards black arrow вверх чёрный стрелка',
    '⬇️': 'downwards black arrow вниз чёрный стрелка',
    '↗️': 'north east arrow стрелка',
    '↘️': 'south east arrow стрелка',
    '↙️': 'south west arrow стрелка',
    '↖️': 'north west arrow стрелка',
    '↕️': 'up down arrow вверх вниз стрелка',
    '↔️': 'left right arrow влево вправо стрелка',
    '↪️': 'rightwards arrow hook вправо стрелка',
    '↩️': 'leftwards arrow hook влево стрелка',
    '⤴️': 'arrow pointing rightwards then curving upwards стрелка указывает вправо вверх',
    '⤵️': 'arrow pointing rightwards then curving downwards стрелка указывает вправо вниз',
    '🔀': 'twisted rightwards arrows вправо',
    '🔁': 'clockwise rightwards leftwards open circle arrows по часовой вправо влево открытый круг',
    '🔂': 'clockwise rightwards leftwards open circle arrows circled one overlay по часовой вправо влево открытый круг в кружке один',
    '🔄': 'anticlockwise downwards upwards open circle arrows вниз вверх открытый круг',
    '🔃': 'clockwise downwards upwards open circle arrows по часовой вниз вверх открытый круг',
    '🎵': 'musical note музыка нота',
    '🎶': 'multiple musical notes музыка ноты',
    '➕': 'heavy plus жирный плюс',
    '➖': 'heavy minus жирный минус',
    '➗': 'heavy division жирный',
    '✖️': 'heavy multiplication x жирный',
    '🟰': 'равно equals',
    '♾️': 'permanent paper бумага',
    '💲': 'heavy dollar жирный доллар',
    '💱': 'currency exchange валюта обмен',
    '™️': 'trade mark торговая знак',
    '©️': 'copyright копирайт',
    '®️': 'registered зарегистрировано',
    '〰️': 'wavy dash волнистая пар',
    '➰': 'curly loop завиток петля',
    '➿': 'double curly loop двойной завиток петля',
    '🔚': 'end leftwards arrow above конец влево стрелка',
    '🔙': 'back leftwards arrow above назад влево стрелка',
    '🔛': 'exclamation mark left right arrow above восклицательный знак влево вправо стрелка',
    '🔝': 'top upwards arrow above вверх стрелка',
    '🔜': 'soon rightwards arrow above скоро вправо стрелка',
    '✔️': 'heavy check mark жирный галочка знак',
    '☑️': 'ballot box check галочка квадрат',
    '🔘': 'radio button радио кнопка',
    '🔴': 'large red circle большой рыжий красный круг',
    '🟠': 'large orange circle большой оранжевый круг',
    '🟡': 'large yellow circle большой жёлтый круг',
    '🟢': 'large green circle большой зелёный круг',
    '🔵': 'large blue circle большой синий круг',
    '🟣': 'large purple circle большой фиолетовый круг',
    '⚫': 'medium black circle средний чёрный круг',
    '⚪': 'medium white circle средний белый круг',
    '🟤': 'large brown circle большой коричневый круг',
    '🔺': 'up pointing red triangle вверх указывает рыжий красный треугольник',
    '🔻': 'down pointing red triangle вниз указывает рыжий красный треугольник',
    '🔸': 'small orange diamond маленький оранжевый ромб',
    '🔹': 'small blue diamond маленький синий ромб',
    '🔶': 'large orange diamond большой оранжевый ромб',
    '🔷': 'large blue diamond большой синий ромб',
    '🔳': 'white square button белый квадрат кнопка',
    '🔲': 'black square button чёрный квадрат кнопка',
    '▪️': 'black small square чёрный маленький квадрат',
    '▫️': 'white small square белый маленький квадрат',
    '◾': 'black medium small square чёрный средний маленький квадрат',
    '◽': 'white medium small square белый средний маленький квадрат',
    '◼️': 'black medium square чёрный средний квадрат',
    '◻️': 'white medium square белый средний квадрат',
    '🟥': 'large red square большой рыжий красный квадрат',
    '🟧': 'large orange square большой оранжевый квадрат',
    '🟨': 'large yellow square большой жёлтый квадрат',
    '🟩': 'large green square большой зелёный квадрат',
    '🟦': 'large blue square большой синий квадрат',
    '🟪': 'large purple square большой фиолетовый квадрат',
    '⬛': 'black large square чёрный большой квадрат',
    '⬜': 'white large square белый большой квадрат',
    '🟫': 'large brown square большой коричневый квадрат',
    '🔈': 'speaker динамик звук',
    '🔇': 'speaker cancellation stroke динамик звук',
    '🔉': 'speaker one sound wave динамик звук один',
    '🔊': 'speaker three sound waves динамик звук три',
    '🔔': 'bell колокольчик',
    '🔕': 'bell cancellation stroke колокольчик',
    '📣': 'cheering megaphone мегафон',
    '📢': 'public address loudspeaker громкоговоритель',
    '💬': 'speech balloon речь облачко чат сообщение',
    '💭': 'thought balloon мысль облачко',
    '🗯️': 'right anger bubble вправо гнев облачко',
    '♠️': 'black spade suit чёрный пики масть',
    '♣️': 'black club suit чёрный трефы масть',
    '♥️': 'black heart suit чёрный сердце любовь масть',
    '♦️': 'black diamond suit чёрный ромб масть',
    '🃏': 'playing card black joker карта карточка чёрный джокер',
    '🎴': 'flower playing cards цветок карты',
    '🀄': 'mahjong tile red dragon маджонг кость рыжий красный дракон',
    '🕐': 'clock face one oclock часы лицо один часов',
    '🕑': 'clock face two oclock часы лицо два часов',
    '🕒': 'clock face three oclock часы лицо три часов',
    '🕓': 'clock face four oclock часы лицо четыре часов',
    '🕔': 'clock face five oclock часы лицо пять часов',
    '🕕': 'clock face six oclock часы лицо шесть часов',
    '🕖': 'clock face seven oclock часы лицо семь часов',
    '🕗': 'clock face eight oclock часы лицо восемь часов',
    '🕘': 'clock face nine oclock часы лицо девять часов',
    '🕙': 'clock face ten oclock часы лицо десять часов',
    '🕚': 'clock face eleven oclock часы лицо часов',
    '🕛': 'clock face twelve oclock часы лицо часов',
};
